Map2u\CoreBundle\Entity\BaseTag:
    type: mappedSuperclass
    fields:
        userId:	        
            type: guid
            unsigned: false
            nullable: true
            column: user_id
        public:	        
            type: boolean
            nullable: true
            column: public
            options:
                default: false
        name:     
            type: string
            length: 50
            fixed: false
            nullable: true
            column: name   
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
        description:
            type: text
            nullable: true
            column: description
    lifecycleCallbacks: 
        prePersist: [prePersist ]
        preUpdate: [preUpdate]
        


