Map2u\CoreBundle\Entity\BaseLayerGeom:
    type: mappedSuperclass
    fields:
        tableId:	        
            type: guid
            unsigned: false
            nullable: true
            column: table_uuid
        tableName:	        
            type: string
            length: 150
            fixed: false
            nullable: true
            column: table_name            
        rowId:	        
            type: guid
            unsigned: false
            nullable: true
            column: row_uuid
        layerId:	        
            type: guid
            unsigned: false
            nullable: false
            column: layer_uuid
        name:     
            type: string
            length: 50
            fixed: false
            nullable: true
            column: name
        style:     
            type: text
            nullable: true
            column: style            
        value:     
            type: string
            length: 250
            fixed: false
            nullable: true
            column: value
        theGeom:
            type: geometry
            nullable: true
     #       requireSQLConversion: true
            column: the_geom
    lifecycleCallbacks: {  }
