Map2u\CoreBundle\Entity\BaseReport:
    type: mappedSuperclass
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            column: id
            generator:
                strategy: UUID
        userId:	        
            type: guid
            unsigned: false
            nullable: true
            column: user_uuid
        sessionid:     
            type: string
            length: 255
            fixed: false
            nullable: true
            column: session_id     
        reportTitle:     
            type: string
            length: 50
            fixed: false
            nullable: true
            column: report_title            
        reportType:     
            type: string
            length: 50
            fixed: false
            nullable: true
            column: report_type            
        name:     
            type: string
            length: 50
            fixed: false
            nullable: true
            column: report_name
      
        deleted:
            type: boolean
            nullable: true
            column: deleted
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
        description:
            type: text
            nullable: true
            column: description
#    manyToOne:
#        user:
#            targetEntity: Application\Sonata\UserBundle\Entity\User
#            cascade: {  }
#            mappedBy: null
#            inversedBy: areas
#            joinColumns:
#                user_id:
#                    referencedColumnName: id
#            orphanRemoval: false
#        project:
#            targetEntity: Project
#            cascade: {  }
#            mappedBy: null
#            inversedBy: reports
#            joinColumns:
#                project_id:
#                    referencedColumnName: id
#            orphanRemoval: false    
#    manyToMany:
#        tags:
#          targetEntity: Map2u\CoreBundle\Entity\Tag
#          inversedBy: {}
#          joinTable:
#                name: manifold_reports_tags
#                joinColumns:
#                  tag_id:
#                    referencedColumnName: id
#                inverseJoinColumns:
#                  report_id:
#                    referencedColumnName: id
#          orphanRemoval: false    
#        categories:
#          targetEntity: Map2u\CoreBundle\Entity\Category
#          inversedBy: {}
#          joinTable:
#                name: manifoldtag_reports_categories
#                joinColumns:
#                  report_id:
#                    referencedColumnName: id
#                inverseJoinColumns:
#                  category_id:
#                    referencedColumnName: id
#          orphanRemoval: false               
    lifecycleCallbacks: {  }
