Map2u\CoreBundle\Entity\BaseSymbolizedLayer:
    type: mappedSuperclass
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        seq:     
            type: integer
            unsigned: false
            nullable: true
            column: seq            
        minZoom:     
            type: integer
            unsigned: false
            nullable: true
            column: min_zoom            
        maxZoom:     
            type: integer
            unsigned: false
            nullable: true
            column: max_zoom            
        title:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: title
        name:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: name
        defaultSldName:    
            type: string
            length: 255
            fixed: false
            nullable: true
            column: defaultsld_name
        labelField:     
            type: string
            length: 250
            fixed: false
            nullable: true
            column: label_field
        tipField:     
            type: string
            length: 250
            fixed: false
            nullable: true
            column: tip_field        
        defaultShowOnMap:
            type: boolean
            column: default_show_on_map
            options:
                default: true
        published:
            type: boolean
            nullable: true
            column: published
        public:
            type: boolean
            nullable: true
            column: public    
        topojsonOnly:
            type: boolean
            nullable: true
            column: topojson_only
        contentFields:
            type: text
            fixed: false
            nullable: true
            column: content_fields
        layerShowInSwitcher:
            type: boolean
            nullable: true
            column: layer_showinswitcher
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        description:
            type: text
            nullable: true
  
    lifecycleCallbacks: 
        prePersist: [prePersist ]
        preUpdate: [preUpdate]
        
