Map2u\CoreBundle\Entity\Country:
    type: entity
    table: map2u_core__country
    gedmo:
        translation:
            locale: locale
            # using specific personal translation class:
            entity: Map2u\CoreBundle\Entity\CountryTranslation     
    fields:
        id:
            id: true
            type: guid
            nullable: false
            generator:
                strategy: UUID
        code:
            type: string
            length: 10
            fixed: false
            nullable: false
            column: code         
        lng:
            type: float
            nullable: false
            column: lng            
        lat:
            type: float
            nullable: false
            column: lat
        zoomLevel:
            type: integer
            unsigned: false
            nullable: false
            column: zoom_level
    lifecycleCallbacks: {  }
