Map2u\CoreBundle\Entity\CountryTranslation:
    type: entity
    table: map2u_core__country_translation
    fields:
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: name            
    lifecycleCallbacks: {  }
