Map2u\CoreBundle\Entity\LayerTranslation:
    type: entity
    table: map2u_core__layer_translation
    fields:
        title:     
            type: string
            length: 250
            fixed: false
            nullable: true
            column: title   
        description:
            type: text
            nullable: true
            column: description
