Map2u\CoreBundle\Entity\LayerCategory:
    type: entity
    table: map2u_core__layer_category
    gedmo:
        translation:
            locale: locale
            # using specific personal translation class:
            entity: Map2u\CoreBundle\Entity\LayerCategoryTranslation           
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            columnDefinition: uuid NOT NULL DEFAULT uuid_generate_v4()
            generator:
                strategy: UUID           
    manyToOne:    
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: {}
            joinColumns:
                user_id:
                    referencedColumnName: id 
        parent:
            targetEntity: Map2u\CoreBundle\Entity\LayerCategory
            inversedBy: children
            joinColumns:
                parent_id:
                    referencedColumnName: id 
    oneToMany:
         children:
            targetEntity: Map2u\CoreBundle\Entity\LayerCategory
            mappedBy: parent
            cascade: ["persist","remove"]