Map2u\CoreBundle\Entity\Layer:
    type: entity
    table: map2u_core__layer
    gedmo:
        translation:
            locale: locale
            # using specific personal translation class:
            entity: Map2u\CoreBundle\Entity\LayerTranslation           
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID           
    oneToMany:    
        layergeoms:
            targetEntity: Map2u\CoreBundle\Entity\LayerGeom
            mappedBy: layer
        symbolizedLayers:
            targetEntity: Map2u\CoreBundle\Entity\SymbolizedLayer
            mappedBy: layer
            
    manyToMany:    
        maps:
            targetEntity: Map2u\CoreBundle\Entity\Map
            inversedBy: layers            
            joinTable:
               name: map2u_core__maps_layers
               joinColumns:
                 layer_uuid:
                   referencedColumnName: id
               inverseJoinColumns:
                 map_uuid:
                   referencedColumnName: id    
        groups:
            targetEntity: Map2u\CoreBundle\Entity\UserGroup
            joinTable:
                   name: map2u_core__layers_groups
                   joinColumns:
                     group_uuid:
                       referencedColumnName: id
                   inverseJoinColumns:
                     layer_uuid:
                       referencedColumnName: id           
    manyToOne:    
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: {}
            joinColumns:
                user_uuid:
                    referencedColumnName: id          
        spatialfile:
            targetEntity: Map2u\CoreBundle\Entity\SpatialFile
            inversedBy: {}
            joinColumns:
                spatialfile_uuid:
                    referencedColumnName: id          
        category:
            targetEntity: Map2u\CoreBundle\Entity\Category
            inversedBy: {}
            joinColumns:
                category_uuid:
                    referencedColumnName: id      
        layerCategory:
            targetEntity: Map2u\CoreBundle\Entity\LayerCategory
            inversedBy: {}
            joinColumns:
                layercategory_uuid:
                    referencedColumnName: id   
    
