Map2u\CoreBundle\Entity\MapBookmark:
    type: entity
    table: map_bookmark
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        name:
            type: string
            length: 255
            nullable: true
            column: name
        address:
            type: string
            length: 255
            nullable: true
            column: address       
        scaleText:
            type: string
            length: 255
            nullable: true
            column: scale_text                   
        userId:     
            type: guid
            unsigned: false
            nullable: false
            column: user_uuid
        seq:     
            type: integer
            unsigned: false
            nullable: true
            column: seq            
        zoomLevel:
            type: integer
            unsigned: false
            nullable: false
            column: zoom_level
        lat:
            type: float
            nullable: false
            column: lat
        lng:
            type: float
            nullable: false
            column: lng
        description:
            type: text
            nullable: true
            column: description
        default:
            type: boolean
            nullable: true
            column: default_bookmark
        createdAt:
            type: datetime
            nullable: true
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
            gedmo:
              timestampable:
                on: update
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            joinColumns:
                user_uuid:
                    referencedColumnName: id
            orphanRemoval: true            
    lifecycleCallbacks: {  }
