Map2u\CoreBundle\Entity\MapLayer:
    type: entity
    table: map2u_core__maps_layers    

    manyToOne:    
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: {}
            joinColumns:
                user_id:
                    referencedColumnName: id          
        category:
            targetEntity: Map2u\CoreBundle\Entity\Category
            inversedBy: {}
            joinColumns:
                category_id:
                    referencedColumnName: id               
        map:
            targetEntity: Map2u\CoreBundle\Entity\Map
            inversedBy: {}
            joinColumns:
                map_id:
                    referencedColumnName: id          
        layer:
            targetEntity: Map2u\CoreBundle\Entity\Layer
            inversedBy: {}
            joinColumns:
                layer_id:
                    referencedColumnName: id          
 