Map2u\CoreBundle\Entity\Region:
    type: entity
    table: map2u_core__region
    fields:
        id:
            id: true
            type: guid
            nullable: false
            generator:
                strategy: UUID
        countryId:
            type: guid
            unsigned: false
            nullable: true
            column: country_id
        lng:
            type: float
            nullable: false
            column: lng
        lat:
            type: float
            nullable: false
            column: lat
        zoomLevel:
            type: integer
            unsigned: false
            nullable: false
            column: zoom_level
        cityId:
            type: guid
            unsigned: false
            nullable: true
            column: city_id
    lifecycleCallbacks: {  }
