Map2u\CoreBundle\Entity\Report:
    type: entity
    table: map2u_reports

    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            inversedBy: {}
            joinColumns:
                user_uuid:
                    referencedColumnName: id
            orphanRemoval: false
        project:
            targetEntity: Project
            cascade: {  }
            inversedBy: reports
            joinColumns:
                project_uuid:
                    referencedColumnName: id
            orphanRemoval: false    
#    manyToMany:
#        tags:
#          targetEntity: Map2u\CoreBundle\Entity\Tag
#          inversedBy: {}
#          joinTable:
#                name: manifold_reports_tags
#                joinColumns:
#                  tag_id:
#                    referencedColumnName: id
#                inverseJoinColumns:
#                  report_id:
#                    referencedColumnName: id
#          orphanRemoval: false    
#        categories:
#          targetEntity: Map2u\CoreBundle\Entity\Category
#          inversedBy: {}
#          joinTable:
#                name: manifoldtag_reports_categories
#                joinColumns:
#                  report_id:
#                    referencedColumnName: id
#                inverseJoinColumns:
#                  category_id:
#                    referencedColumnName: id
#          orphanRemoval: false               
    lifecycleCallbacks: {  }
