Map2u\CoreBundle\Entity\SpatialFile:
    type: entity
    table: map2u_core__spatialfile
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
#            columnDefinition: uuid NOT NULL DEFAULT uuid_generate_v4()
            generator:
                strategy: UUID   
  
    manyToOne:    
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: {}
            joinColumns:
                user_uuid:
                    referencedColumnName: id 
#        parent:
#            targetEntity: Map2u\CoreBundle\Entity\Category
#            inversedBy: children
#            joinColumns:
#                parent_id:
#                    referencedColumnName: id 
#    oneToMany:
#         children:
#            targetEntity: Map2u\CoreBundle\Entity\Category
#            mappedBy: parent
#            cascade: ["persist","remove"]
#         maplayers:
#            targetEntity: MapLayer
#            cascade: ["persist","remove"]
#            mappedBy: category                 