Map2u\CoreBundle\Entity\SymbolizedLayer:
    type: entity
    table: map2u_core__symbolizedlayers    
    gedmo:
        translation:
            locale: locale
            # using specific personal translation class:
            entity: Map2u\CoreBundle\Entity\SymbolizedLayerTranslation           

    manyToOne:    
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: symbolizedLayers
            joinColumns:
                user_uuid:
                    referencedColumnName: id          
        layerCategory:
            targetEntity: Map2u\CoreBundle\Entity\LayerCategory
            inversedBy: {}
            joinColumns:
                layercategory_uuid:
                    referencedColumnName: id               
        category:
            targetEntity: Map2u\CoreBundle\Entity\Category
            inversedBy: {}
            joinColumns:
                category_uuid:
                    referencedColumnName: id               
        map:
            targetEntity: Map2u\CoreBundle\Entity\Map
            inversedBy: symbolizedLayers
            joinColumns:
                map_uuid:
                    referencedColumnName: id          
        layer:
            targetEntity: Map2u\CoreBundle\Entity\Layer
            inversedBy: symbolizedLayers
            joinColumns:
                layer_uuid:
                    referencedColumnName: id          
 