Map2u\CoreBundle\Entity\SystemSettings:
    type: entity
    table: system_settings
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID
        userId:     
            type: guid
            unsigned: false
            nullable: false
            column: user_id
        name:
            type: string
            length: 250
            fixed: false
            nullable: false
            column: name
        settings:
            type: text
            nullable: true
            column: settings
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        description:
            type: text
            nullable: true
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: true        
    lifecycleCallbacks: {  }
