Map2u\CoreBundle\Entity\ThematicMap:
    type: entity
    table: thematic_map
    fields:
        id:
            id: true
            type: guid
            unsigned: false
            nullable: false
            generator:
                strategy: UUID              
        datasourceId:
            type: integer
            unsigned: false
            nullable: false
            column: datasource_id
        fieldname:
            type: string
            length: 255
            nullable: false
            column: fieldname
        gradient:
            type: string
            length: 255
            nullable: false
            column: gradient

    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: true   
        category:
            targetEntity: Category
            cascade: ["persist","remove"]
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false                                     
            
    lifecycleCallbacks: {  }
