parameters:
services:
    map2u_core.block.fixed_topmenu:
                class: Map2u\CoreBundle\Block\FixedTopmenuBlockService
                arguments:
                    - "map2u_core.block.fixed_topmenu"
                    - "@templating"
                    - @doctrine.orm.entity_manager
                tags:
                    -  { name: sonata.block, alias: map2u_core.block.fixed_topmenu}   
     
    map2u_core.block.uploadspatialfile:
                    class: Map2u\CoreBundle\Block\UploadSpatialFileBlockService
                    arguments:
                        - "map2u_core.block.uploadspatialfile"
                        - "@templating"
                        - @service_container
                        - @doctrine.orm.entity_manager
                    tags:
                        - {name: "sonata.block"}   
                        
    map2u_core.authentication.success_handler:
        class: Map2u\CoreBundle\Listener\AuthenticationSuccessHandler
        arguments:  [@security.http_utils, [], @router]
        
#        parent: security.authentication.success_handler
        

    map2u_core.authentication.failure_handler:
        class: Map2u\CoreBundle\Listener\AuthenticationFailureHandler
        parent: security.authentication.failure_handler  
        
 
            
    map2u_core.twig_core.map2u_extension:
        class: Map2u\CoreBundle\Twig\Map2uExtension
        tags:
            - { name: twig.extension }
    map2u_core.registration.form.type:
        class: Map2u\CoreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: map2u_user_registration }
    map2u_core.admin.sidebar_menu:
        class: Map2u\CoreBundle\Admin\SidebarMenuAdmin
        arguments: [~, Map2u\CoreBundle\Entity\SidebarMenu, Map2uCoreBundle:SidebarMenuAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Sidebar Menu }
    map2u_core.manager.category:
        class: %map2u.core.manager.category.class%
        arguments: [Map2u\CoreBundle\Entity\Category,@doctrine, @security.context]
    
    map2u_core.form.type.category_selector:  
        class: Map2u\CoreBundle\Form\Type\CategorySelectorType
        arguments: ["@map2u_core.manager.category"]
        tags:
            - { name: form.type, alias: map2u_core_category_selector }  
            
    map2u_core.manager.sidebarmenu:
        class: %map2u.core.manager.sidebarmenu.class%
        arguments: [Map2u\CoreBundle\Entity\SidebarMenu,@doctrine, @security.context,@service_container]
    
    map2u_core.form.type.sidebarmenu_selector:  
        class: Map2u\CoreBundle\Form\Type\SidebarMenuSelectorType
        arguments: ["@map2u_core.manager.sidebarmenu"]
        tags:
            - { name: form.type, alias: map2u_core_sidebarmenu_selector }                               
    map2u_core.locale:
        class:   Map2u\CoreBundle\Listener\LocaleListener
        tags:
            - {name: kernel.event_listener, event: kernel.request,  method: onKernelRequest }  
            
    map2u_core.admin.layer_category:
        class: Map2u\CoreBundle\Admin\LayerCategoryAdmin
        arguments: [~, Map2u\CoreBundle\Entity\LayerCategory, Map2uCoreBundle:LayerCategoryAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Map and Layer, label: Layer Category }
    map2u_core.admin.map:
        class: Map2u\CoreBundle\Admin\MapAdmin
        arguments: [~, Map2u\CoreBundle\Entity\Map, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Map and Layer, label: Map }

    map2u_core.admin.symbolized_layer:
        class: Map2u\CoreBundle\Admin\SymbolizedLayerAdmin
        arguments: [~, Map2u\CoreBundle\Entity\SymbolizedLayer, Map2uCoreBundle:SymbolizedLayerAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Map and Layer, label: Map Layer }
            
    map2u_core.admin.layer:
        class: Map2u\CoreBundle\Admin\LayerAdmin
        arguments: [~, Map2u\CoreBundle\Entity\Layer, Map2uCoreBundle:LayerAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Map and Layer, label: Layer }


    map2u_core.admin.country:
        class: Map2u\CoreBundle\Admin\CountryAdmin
        arguments: [~, Map2u\CoreBundle\Entity\Country, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Region, label: Country }

    map2u_core.admin.state:
        class: Map2u\CoreBundle\Admin\StateAdmin
        arguments: [~, Map2u\CoreBundle\Entity\State, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Region, label: State }

    map2u_core.admin.city:
        class: Map2u\CoreBundle\Admin\CityAdmin
        arguments: [~, Map2u\CoreBundle\Entity\City, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Region, label: City }

    map2u_core.admin.region:
        class: Map2u\CoreBundle\Admin\RegionAdmin
        arguments: [~, Map2u\CoreBundle\Entity\Region, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Region, label: Region }

    map2u_core.admin.spatial_file:
        class: Map2u\CoreBundle\Admin\SpatialFileAdmin
        arguments: [~, Map2u\CoreBundle\Entity\SpatialFile, Map2uCoreBundle:SpatialFileAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Map and Layer, label: Spatial File }

    map2u_core.admin.category:
        class: Map2u\CoreBundle\Admin\CategoryAdmin
        arguments: [~, Map2u\CoreBundle\Entity\Category, Map2uCoreBundle:CategoryAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Category }
            